model:
  arch: sqnet
  backbone:
    arch: dgcnn
    use_spatial_transform: False
    use_mean_global_feature: False
    use_batch_norm: False
    k: 20
    leakyrelu_slope: 0.2
    input_dim: 3
    l_hidden_local: [64, 64, 128, 256]
    global_feature_dim: 1024
  position:
    l_hidden: [512, 256]
    output_dim: 3
  orientation:
    l_hidden: [512, 256]
    output_dim: 4
  size:
    l_hidden: [512, 256]
    output_dim: 3
  shape:
    l_hidden: [512, 256]
    output_dim: 2
trainer: recognition
training:
  n_epoch: 100
  loss:
    type: sq_loss
    weight: 0.01
  optimizer:
    name: 'adam'
    lr: 0.001
  # metric:
  #   type: iou
  print_interval: 100
  val_interval: 2000
  save_interval: 1000
  visualize_number: 3
  visualize_interval: 1000
data:
  training:
    loader: primitive
    object_types: ['box', 'cone', 'cylinder', 'truncated_cone', 'ellipsoid', 'truncated_torus']
    num_points: 1500
    num_gt_points: 1500
    num_sampled_points: 300    
    noise_augment: True
    noise_std: 0.001
    path: datasets/primitive_dataset
    csv_name: 'train_datalist.csv'
    batch_size: 16
    num_workers: 8
  validation:
    loader: primitive
    object_types: ['box', 'cone', 'cylinder', 'truncated_cone', 'ellipsoid', 'truncated_torus']
    num_points: 1500
    num_gt_points: 1500
    num_sampled_points: 300  
    noise_augment: True
    noise_std: 0.001
    path: datasets/primitive_dataset
    csv_name: 'validation_datalist.csv'
    batch_size: 16
    num_workers: 8
  test:
    loader: primitive
    object_types: ['box', 'cone', 'cylinder', 'truncated_cone', 'ellipsoid', 'truncated_torus']
    num_points: 1500
    num_gt_points: 1500
    num_sampled_points: 300  
    noise_augment: True
    noise_std: 0.001
    path: datasets/primitive_dataset
    csv_name: 'test_datalist.csv'
    batch_size: 16
    num_workers: 8
   
